services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx/
      args:
        - NGINX_PORT=${NGINX_PORT}
        - WORDPRESS_PORT=${WORDPRESS_PORT}
    depends_on:
      - wordpress
    restart: always
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    environment:
      - DOMAINE_NAME=${DOMAINE_NAME}
      - NGINX_PORT=${NGINX_PORT}
      - WORDPRESS_PORT=${WORDPRESS_PORT}
    volumes:
      - wp_data:/var/www/wordpress
    networks:
      - inception_network

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb/
      args:
        - MARIADB_PORT=${MARIADB_PORT}
    restart: always
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD_FILE=/run/secrets/db_password
      - DB_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - MARIADB_PORT=${MARIADB_PORT}
    secrets:
      - db_password
      - db_root_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception_network

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress/
      args:
        - WORDPRESS_PORT=${WORDPRESS_PORT}
        - MARIADB_PORT=${MARIADB_PORT}
        - REDIS_PORT=${REDIS_PORT}
    restart: always
    depends_on:
      - mariadb
      - redis
    environment:
      - DOMAINE_NAME=${DOMAINE_NAME}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD_FILE=/run/secrets/db_password
      - WP_USER=${WP_USER}
      - WP_USER_EMAIL=${WP_USER_EMAIL}
      - WP_USER_PASSWORD_FILE=/run/secrets/wp_user_password
      - WP_ADMIN=${WP_ADMIN}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_ADMIN_PASSWORD_FILE=/run/secrets/wp_admin_password
      - WORDPRESS_PORT=${WORDPRESS_PORT}
      - MARIADB_PORT=${MARIADB_PORT}
      - REDIS_PORT=${REDIS_PORT}
    secrets:
      - db_password
      - wp_user_password
      - wp_admin_password
    volumes:
      - wp_data:/var/www/wordpress
    networks:
      - inception_network
  
  redis:
    container_name: redis
    build:
      context: ./requirements/bonus/redis/
      args:
        - REDIS_PORT=${REDIS_PORT}
    restart: always
    environment:
      - REDIS_PORT=${REDIS_PORT}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - inception_network
  
  ftp:
    container_name: ftp
    build: ./requirements/bonus/ftp/
    depends_on:
      - wordpress
    restart: always
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    volumes:
      - wp_data:/var/www/wordpress
    environment:
      - FTP_USER=${FTP_USER}
      - FTP_PASSWORD_FILE=/run/secrets/ftp_password
    secrets:
      - ftp_password
    networks:
      - inception_network

  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer/
    restart: always
    ports:
      - "8081:8081"
    networks:
      - inception_network

  website:
    container_name: website
    build:
      context: ./requirements/bonus/website/
      args:
        - WEBSITE_PORT=${WEBSITE_PORT}
    restart: always
    environment:
      - WEBSITE_PORT=${WEBSITE_PORT}
    ports:
      - "${WEBSITE_PORT}:${WEBSITE_PORT}"
    networks:
      - inception_network

  cadvisor:
    container_name: cadvisor
    build: ./requirements/bonus/cadvisor
    depends_on:
      - nginx
      - mariadb
      - wordpress
      - website
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - inception_network

secrets:
  db_password:
    file: ${DB_PASSWORD_FILE}
  db_root_password:
    file: ${DB_ROOT_PASSWORD_FILE}
  wp_user_password:
    file: ${WP_USER_PASSWORD_FILE}
  wp_admin_password:
    file: ${WP_ADMIN_PASSWORD_FILE}
  ftp_password:
    file: ${FTP_PASSWORD_FILE}

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: /home/zzaoui/data/mariadb
      o: bind
  wp_data:
    driver: local
    driver_opts:
      type: none
      device: /home/zzaoui/data/wordpress
      o: bind

networks:
  inception_network:
    driver: bridge